name: advent_of_code_2023
description: Advent of Code 2023 challenge solutions.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dev_dependencies:
  test: ^1.19.2
  very_good_analysis: ^4.0.0
